export default {
    fotos: {
      entradas: [
        {
          id: 1,
          nombre: "Ensaladilla Rusa",
          imagen: "./src/images/menu-1.png",
          precio: 25.5,
          ingredientes: "Con Mahonesa de Oliva Virgen Extra y Bonito.",
        },
        {
          id: 2,
          nombre: "Salpicón de Aguacate",
          imagen: "./assets/imagens/menu-2.png",
          precio: 25.5,
          ingredientes: "Con Langostinos y Mahonesa de Mostaza.",
        },
      ],
      pescadosCarnes: [
        {
          id: 3,
          nombre: "Lomos de Boquerón",
          imagen: "./assets/imagens/menu-3.png",
          precio: 25.5,
          ingredientes: "Al natural con Tomate Dulce y Miel de Caña.",
        },
        {
          id: 4,
          nombre: "Gambas de Málaga",
          imagen: "./assets/imagens/menu-4.png",
          precio: 25.5,
          ingredientes: "Al Pil-pil y Papada Ibérica de Bellota.",
        },
        {
          id: 5,
          nombre: "Verduras de temporada",
          imagen: "./assets/imagens/menu-5.png",
          precio: 25.5,
          ingredientes: "Fritas con Foie y Huevo.",
        },
      ],
      arrocesFideuas: [
        {
          id: 6,
          nombre: "Arroz en Paella",
          imagen: "./assets/imagens/menu-6.png",
          precio: 30.0,
          ingredientes: "Ingredientes de la paella...",
        },
        {
          id: 7,
          nombre: "Arroz Caldoso",
          imagen: "./assets/imagens/menu-7.png",
          precio: 28.5,
          ingredientes: "Ingredientes del arroz caldoso...",
        },
        {
          id: 8,
          nombre: "Fideuá",
          imagen: "./assets/imagens/menu-8.png",
          precio: 27.0,
          ingredientes: "Ingredientes de la fideuá...",
        },
      ],
      postres: [
        {
          id: 9,
          nombre: "Tiramisú",
          imagen: "./assets/imagens/dessert-1.jpg",
          precio: 12.99,
          ingredientes: "Bizcochos, café, queso mascarpone y cacao en polvo.",
        },
        {
          id: 10,
          nombre: "Cheesecake de Fresa",
          imagen: "./assets/imagens/dessert-2.jpg",
          precio: 15.5,
          ingredientes: "Base de galleta, queso crema, y topping de fresas frescas.",
        },
        {
          id: 11,
          nombre: "Brownie con Helado",
          imagen: "./assets/imagens/dessert-3.jpg",
          precio: 14.75,
          ingredientes: "Brownie de chocolate caliente con helado de vainilla.",
        },
        {
          id: 12,
          nombre: "Mousse de Chocolate",
          imagen: "./assets/imagens/dessert-4.jpg",
          precio: 11.99,
          ingredientes: "Chocolate negro, huevos, azúcar y nata montada.",
        },
        {
          id: 13,
          nombre: "Frutas Frescas",
          imagen: "./assets/imagens/dessert-5.jpg",
          precio: 9.99,
          ingredientes: "Selección de frutas frescas de temporada.",
        },
      ],
      bebidas: [
        {
          id: 14,
          nombre: "Margarita",
          imagen: "./assets/imagens/drink-1.jpg",
          precio: 8.99,
          ingredientes: "Tequila, triple sec, jugo de lima y sal en el borde del vaso.",
        },
        {
          id: 15,
          nombre: "Mojito",
          imagen: "./assets/imagens/drink-2.jpg",
          precio: 7.5,
          ingredientes: "Ron, azúcar, menta, lima y soda.",
        },
        {
          id: 16,
          nombre: "Piña Colada",
          imagen: "./assets/imagens/drink-3.jpg",
          precio: 9.25,
          ingredientes: "Ron, crema de coco, piña y hielo.",
        },
        {
          id: 17,
          nombre: "Café Espresso",
          imagen: "./assets/imagens/drink-4.jpg",
          precio: 5.99,
          ingredientes: "Café fuerte servido en pequeñas cantidades.",
        },
        {
          id: 18,
          nombre: "Agua Mineral con Gas",
          imagen: "./assets/imagens/drink-5.jpg",
          precio: 3.99,
          ingredientes: "Agua mineral con gas, servida con hielo y rodaja de limón.",
        },
      ],
    },
  };
  